baseURL = "https://mugenbatscha.me"
languageCode = "en-uk"
title = "Fabian's Blog"
theme = "mugenbatscha"
enableRobotsTXT = true
relativeURLs=true
# disableKinds = ['taxonomy', 'term']

[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Fabian"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#494f5c"

  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    name = "About"
    pre = "user"
    url = "/about/"
    weight = 1
#  [[menu.main]]
#    name = "Impressum Placeholder"
#    pre = "info"
#    url = "/impressum/"
#    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "RSS"
    pre = "rss"
    url = "/index.xml"
    weight = 4
  [[menu.main]]
    name = "Blog"
    pre = "globe"
    url = "/posts"
    weight = 5

  [[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/mugenbatscha"
    pre = "twitter"
    weight = 6
  [[menu.social]]
    name = "Instagram"
    url = "https://www.instagram.com/mugenbatscha/"
    pre = "instagram"
    weight = 7
  [[menu.social]]
    name = "Github"
    url = "https://github.com/lauwarm"
    pre = "github"
    weight = 8
  [[menu.social]]
    name = "Twitch"
    url = "https://twitch.tv/mugenbatscha"
    pre = "twitch"
    weight = 9
#  [[menu.social]]
#    name = "Komoot"
#    url = "https://www.komoot.de/user/435509273062"
#    pre = ""
#    weight = 10
